### ISSUE TITLE
adding CentOS Stream8 (and phase out CentOS-8)?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [Xpra-org/repo-build-scripts#5]
Hi

Thanks the multiOS builds! RFE to add Stream8 and deprecate CentOS-8 after 31 dec 2021?

Cheers

Tru

**Comment by totaam** [comment]
At this point, it's not yet clear if `stream8` is a suitable replacement for the centos8 build containers we were using until now.
Perhaps we will go with another distro for building RHEL compatible packages instead, or maybe in addition to this one.

Without even considering the potential ABI issues that may arise now that `stream8` is not guaranteed to be the same as RHEL8, there are a number of key packages missing.
The recommended way of dealing with this is to install the `PowerTools` from `EPEL`.
The big problem with this is that we have never required `EPEL` for anything and that adding this build dependency is likely to result in some runtime dependencies sooner or later too.
Without it, it is impossible to build the patched dummy driver, `pycuda` or even xpra itself:
```
No matching package to install: 'libXres-devel'
No matching package to install: 'libvpx-devel'
No matching package to install: 'libxkbfile-devel'
No matching package to install: 'pandoc'
No matching package to install: 'pygobject3-devel'
No matching package to install: 'turbojpeg-devel'
```

@truatpasteurdotfr you can find some beta `stream8` builds here:
https://xpra.org/beta/CentOS/stream8/

**Comment by truatpasteurdotfr** [comment]
If that can help, epel-next is epel for stream8 `dnf install epel-next-release` , and stream8 is "just" what will become the next RHEL8. And stream8 also has powertools (from centos-stream-repos-8-4.el8). Off course, a downstream clone of your choice is definitely also expected, as "usual".

**Comment by totaam** [comment]
@truatpasteurdotfr thanks for the hint, this helped me solve #6

As for RHEL8, I am reluctant to point to `stream8` as this will always be ahead of what's in RHEL8, and may cause ABI issues.

We now have `oraclelinux:8`, `rockylinux:8` and `almalinux:8.6` builds: https://xpra.org/beta/
(since 92868c21d1fe2963ac1e3070b95396a153a2b898)
As well as some RHEL9 clones too.

I am tempted to just pick one, the one that's easiest to maintain. (ie: they are not all equal when it comes to the number of packages they provide or where to get them from: 449db033976819cfaae60362ed8c6d5b359215c9, d388ec23e097f58190d4cda64af615ed9c488bb6, 4284d30784717cb637fc302cc06a6fe15bc79f1d)

**Comment by totaam** [comment]
I have updated the symlinks for `RedHat`:
* `9` and `8` now point to `almalinux/9` and `almalinux/8`
* `7` points to `CentOS/7`

For `CentOS`:
* `9` still points to `stream9`
* `8` now points to `stream8`
* `7` still points to `7.9.2009`
* `6` still points to `6.10` (unmaintained)

**Comment by totaam** [comment]
We also needed to preserve the `XWorkstation` and `XServer` symlinks in `RedHat`, now done:
```
7 -> ../CentOS/7
7Server -> ../CentOS/7
7Workstation -> ../CentOS/7
8 -> ../almalinux/8
8Server -> ../almalinux/8
8Workstation -> ../almalinux/8
9 -> ../almalinux/9
9Server -> ../almalinux/9
9Workstation -> ../almalinux/9
```
